
!!!.....................................................................
!!!........................PARAMETERS MOD...............................
!!!.....................................................................
!! Sets kinds for real and integer and other parameters used acorss the
!! prsogram
MODULE parameters_mod
 USE, INTRINSIC :: iso_c_binding
 INTEGER(KIND=4),PARAMETER                     ::rk=8,ik=4
 REAL(KIND=rk),PARAMETER                       ::pi=acos(-1._rk)
END MODULE parameters_mod
!!!.....................................................................
!!!.....................................................................
